# To perform and visualize analyses online

## Before the experiment: get everything ready

### imports

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import hydra
from hydra.utils import get_original_cwd
import os
from omegaconf import DictConfig, OmegaConf
from dataclasses import dataclass
from typing import List, Dict, Any

from IPython.display import display

In [3]:
# Load config
import sys
import os
from pathlib import Path


# Add the parent directory to the path so we can import modules properly
cwd = Path.cwd()
print(f"home directory: {cwd}")
relative_repo_path = "GitRepos/simulation_closed_loop"

# append repo path 
sys.path.append(str(cwd / relative_repo_path))

# Import Hydra config utilities
from omegaconf import DictConfig, OmegaConf
import hydra
from hydra.utils import instantiate
from hydra.core.config_store import ConfigStore
from hydra import compose, initialize

# Initialize Hydra with the relative path to the config directory
config_path = os.path.join(relative_repo_path,"config")
print(f"Config path: {config_path}")

# Initialize Hydra
with initialize(version_base="1.3", config_path=config_path):
    # Compose the configuration
    cfg = compose(config_name="config")

# Print the config to verify it loaded correctly
print("Configuration loaded successfully:")
print(OmegaConf.to_yaml(cfg))

home directory: /gpfs01/euler/User/ssuhai
Config path: GitRepos/simulation_closed_loop/config
Configuration loaded successfully:
data_subfolders:
  day: 20250717
  experiment: 1
DJ:
  username: ssuhai
  userinfo:
    experimenter: closedlooptest
    animal_loc: 1
    region_loc: 2
    field_loc: 3
    stimulus_loc: 4
    cond1_loc: 5
    data_dir: /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test
  table_parameters:
    PreprocessParams:
    - preprocess_id: 1
      fs_resample: 60
      stim_names:
      - gChirp
      - lChirp
      - movingbar
      - densenoise
    - preprocess_id: 2
      window_length: 60
      poly_order: 3
      non_negative: 1
      subtract_baseline: 0
      standardize: 1
      stim_names:
      - mouse_cam
    Stimulus:
      noise:
        stim_name: densenoise
        stim_family: noise
        pix_n_x: 20
        pix_n_y: 15
        skip_duplicates: true
        pix_scale_x_um: 40
        pix_scale_y_um: 40
        framerate: 5
    DNoiseTraceParams:
      dnoise_params_id: 1
      fupsample_trace: 20
      fupsample_stim: 4
      ref_time: stim
      fit_kind: gradient
      skip_duplicates: true
      pre_blur_sigma_s: 0.0
      post_blur_sigma_s: 0.0
paths:
  repo_directory: /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/
  home_directory: /gpfs01/euler/User/ssuhai
  dj_config_directory: datajoint
  rgc_output_directory: datajoint/rgc_classifier
  recording_files_dir: /gpfs01/euler/data/Data/Suhai/test_data_klaudia
  stimulus_output_dir: /gpfs01/euler/data/Data/Suhai/stimuli_closed_loop
  dummy_ini_dir: data/dummy_ini/
debug: false
plot_results: true
clean_up_before: true
clean_up_after: false
model_configs:
  data_io:
    stimuli:
      _target_: openretina.data_io.hoefling_2024.stimuli.movies_from_pickle
      _convert_: object
      file_path:
        _target_: openretina.utils.file_utils.get_local_file_path
        _convert_: object
        file_path: ${model_configs.paths.movies_path}
        cache_folder: ${model_configs.paths.cache_dir}
    responses:
      _target_: openretina.data_io.hoefling_2024.responses.make_final_responses
      _convert_: object
      response_type: natural
      data_dict:
        _target_: openretina.data_io.hoefling_2024.responses.filter_responses
        _convert_: object
        filter_cell_types: ${model_configs.quality_checks.filter_cell_types}
        cell_types_list: ${model_configs.quality_checks.cell_types_list}
        chirp_qi: ${model_configs.quality_checks.chirp_qi}
        d_qi: ${model_configs.quality_checks.d_qi}
        qi_logic: ${model_configs.quality_checks.qi_logic}
        filter_counts: ${model_configs.quality_checks.filter_counts}
        classifier_confidence: ${model_configs.quality_checks.classifier_confidence}
        verbose: ${model_configs.quality_checks.verbose}
        all_responses:
          _target_: openretina.utils.h5_handling.load_h5_into_dict
          _convert_: object
          file_path:
            _target_: openretina.utils.file_utils.get_local_file_path
            _convert_: object
            file_path: ${model_configs.paths.responses_path}
            cache_folder: ${model_configs.paths.cache_dir}
  quality_checks:
    filter_cell_types: true
    cell_types_list:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    chirp_qi: 0.35
    d_qi: 0.6
    qi_logic: or
    filter_counts: false
    classifier_confidence: 0.25
    verbose: true
  dataloader:
    _target_: openretina.data_io.hoefling_2024.dataloaders.natmov_dataloaders_v2
    _convert_: object
    batch_size: 128
    train_chunk_size: 50
    allow_over_boundaries: true
    validation_clip_indices:
    - 0
    - 4
    - 10
    - 11
    - 18
    - 30
    - 45
    - 62
    - 67
    - 77
    - 79
    - 80
    - 81
    - 83
    - 95
  model:
    _target_: openretina.models.core_readout.CoreReadout
    _convert_: object
    in_shape:
    - 2
    - 150
    - 18
    - 16
    hidden_channels:
    - 16
    - 16
    temporal_kernel_sizes:
    - 21
    - 11
    spatial_kernel_sizes:
    - 11
    - 5
    core_gamma_input: 0.0
    core_gamma_in_sparse: 0.0
    core_gamma_hidden: 0.0
    core_gamma_temporal: 40.0
    core_input_padding: false
    core_hidden_padding: true
    maxpool_every_n_layers: null
    downsample_input_kernel_size: null
    n_neurons_dict: ???
    readout_scale: true
    readout_bias: true
    readout_gaussian_masks: true
    readout_gaussian_mean_scale: 6.0
    readout_gaussian_var_scale: 4.0
    readout_positive: true
    readout_gamma: 0.4
    learning_rate: 0.01
    cut_first_n_frames_in_core: 0
    dropout_rate: 0.0
  training_callbacks:
    early_stopping:
      _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: val_correlation
      min_delta: 0.001
      patience: 10
      verbose: true
      mode: max
      strict: true
      check_finite: false
    lr_monitor:
      _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: epoch
      log_momentum: true
      log_weight_decay: true
    model_checkpoint:
      _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: ${model_configs.paths.output_dir}/checkpoints
      filename: '{epoch:02d}_{val_correlation:.3f}'
      monitor: val_correlation
      verbose: false
      save_last: false
      save_top_k: 1
      mode: max
      auto_insert_metric_name: true
      save_weights_only: false
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
  logger:
    tensorboard:
      _target_: lightning.pytorch.loggers.TensorBoardLogger
      name: null
      save_dir: ${model_configs.paths.output_dir}/tensorboard/
      prefix: ''
      version: ''
    csv:
      _target_: lightning.pytorch.loggers.csv_logs.CSVLogger
      save_dir: ${model_configs.paths.output_dir}
      name: csv/
      prefix: ''
      version: ''
  trainer:
    _target_: lightning.Trainer
    default_root_dir: ${model_configs.paths.output_dir}
    deterministic: warn
    max_epochs: 100
    gradient_clip_val: 1
    precision: 32-true
    accumulate_grad_batches: 1
  hydra:
    run:
      dir: ${model_configs.paths.log_dir}/openretina_assets/runs/${exp_name}/${now:%Y-%m-%d_%H-%M-%S}
  exp_name: hoefling_2024_core_readout_low_res_filtered
  seed: 42
  check_stimuli_responses_match: false
  is_ensemble_model: true
  paths:
    load_model_path: /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/models/missing_first_ensemble
    cache_dir: ${oc.env:OPENRETINA_CACHE_DIRECTORY}
    log_dir: ${paths.repo_directory}/
    output_dir: output
    movies_path: https://huggingface.co/datasets/open-retina/open-retina/blob/main/euler_lab/hoefling_2024/stimuli/rgc_natstim_18x16_joint_normalized_2024-01-11.zip
    responses_path: https://huggingface.co/datasets/open-retina/open-retina/resolve/main/euler_lab/hoefling_2024/responses/rgc_natstim_2024-08-14.zip
  matmul_precision:
    _target_: torch.set_float32_matmul_precision
    precision: highest
  only_train_readout: true
openretina:
  mei_generation:
    reducer_start: 10
    reducer_length: 10
    max_iteration: 100
    lr: 10
    stimulus_range_constraints:
      norm: 30.0
      x_min_green: -0.654
      x_max_green: 6.269
      x_min_uv: -0.913
      x_max_uv: 6.269
    min_testset_correl: 0.3
    reconstruct_mei: true

In [4]:
from simulations.loop_components.dj_wrappers import DJTableHolder,Preprocessor,QualityAndTypeWrapper,STAWrapper,RandomSeedMEIWrapper
from simulations.loop_components.recording_file_copier import copy_rec_files,create_directory_structure
from simulations.loop_components.stimulus import create_single_mei_avis_and_metadata
from simulations.loop_components.utils import log

### Create processing components (connect them to DB)

In [5]:
# create preprocessor
os.environ["DJ_SUPPORT_FILEPATH_MANAGEMENT"] = "TRUE"

dj_table_holder = DJTableHolder(
                username=cfg.DJ.username, # type: ignore
                
                #paths
                home_directory=cfg.paths.home_directory, # type: ignore
                repo_directory=cfg.paths.repo_directory, # type: ignore
                dj_config_directory= cfg.paths.dj_config_directory, # type: ignore
                rgc_output_directory= cfg.paths.rgc_output_directory, # type: ignore
                data_subfolders=cfg.data_subfolders, # type: ignore


                userinfo= cfg.DJ.userinfo, # type: ignore

                table_parameters=cfg.DJ.table_parameters, # type: ignore

                # from overall configs
                debug=cfg.debug, # type: ignore
                plot_results=cfg.plot_results, # type: ignore
                )

In [6]:
# # # Load config and tables
# dj_table_holder.load_config()
# dj_table_holder.load_tables()
# # # print(" loaded and configured successfully")
# # # # dj_table_holder.clear_tables("experiment")

dj_table_holder.setup()

[2025-09-02 13:32:04,078][INFO]: Connecting ssuhai@172.25.240.200:3306
[2025-09-02 13:32:04,133][INFO]: Connected ssuhai@172.25.240.200:3306

schema_name: ageuler_ssuhai_closed_loop
Done reconnecting. Skipping adding new entries from config.

/gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/simulations/loop_components/dj_wrappers.py:301: UserWarning:
Some DJ tables (like UserInfo) are not empty, skipping adding new entries from config.
Make sure this is wanted. Call clear_tables(`all`) if you want different data in there
  warnings.warn("\nSome DJ tables (like UserInfo) are not empty, skipping adding new entries from config.\nMake sure this is wanted. Call clear_tables(`all`) if you want different data in there")

In [7]:
preprocessor = Preprocessor(dj_table_holder=dj_table_holder)


quality_type_analysis_wrapper = QualityAndTypeWrapper(
    dj_table_holder=dj_table_holder,)

sta_wrapper = STAWrapper(
    dj_table_holder=dj_table_holder,)

random_seed_mei_wrapper = RandomSeedMEIWrapper(
    dj_table_holder=dj_table_holder,
    model_configs=cfg.model_configs, # type: ignore
    mei_generation_params=cfg.openretina.mei_generation, # type: ignore
    seeds=[111,222]
)

## During the experimet

### Move files from server to the repo

In [12]:
create_directory_structure(base_directory= cfg.DJ.userinfo.data_dir,
                           date=  cfg.data_subfolders.day, 
                           experiment = cfg.data_subfolders.experiment)

copy_rec_files(
    recording_files_dir=cfg.paths.recording_files_dir,  # type: ignore
    destination_base=cfg.DJ.userinfo.data_dir,  # type: ignore
    date=cfg.data_subfolders.day,  # type: ignore
    experiment=cfg.data_subfolders.experiment,  # type: ignore
    full_dummy_ini_dir= os.path.join(cfg.paths.repo_directory, cfg.paths.dummy_ini_dir),  # type: ignore
)

SKIPPING File /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/Raw/M1_LR_GCL0_Chirp_iter0.smh already exists, skipping.
SKIPPING File /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/Raw/M1_LR_GCL0_MB_iter0.smh already exists, skipping.
SKIPPING File /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/Raw/M1_LR_GCL0_MC18_iter0.smh already exists, skipping.
SKIPPING File /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/Raw/M1_LR_GCL0_Chirp_iter0.smp already exists, skipping.
SKIPPING File /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/Raw/M1_LR_GCL0_MC18_iter0.smp already exists, skipping.
SKIPPING File /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/Raw/M1_LR_GCL0_DN_iter0.smp already exists, skipping.
SKIPPING File /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/Raw/M1_LR_GCL0_DN_iter0.smh already exists, skipping.
SKIPPING File /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/Raw/M1_LR_GCL0_MB_iter0.smp already exists, skipping.
NO INI FILE found.
COPIED dummy ini file from /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/dummy_ini/dummy.ini to /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/20250717_left.ini

In [15]:
preprocessor.upload_iteration_metadata()

Scanning for experimenter: closedlooptest
	header_path: /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1
		header_name: 20250717_left.ini
		Adding: {'experimenter': 'closedlooptest', 'date': datetime.datetime(2025, 7, 17, 0, 0), 'exp_num': 1}

OpticDisk: 100%|██████████| 1/1 [00:00<00:00, 31.41it/s]

Found 4 files in 1 fields for key={'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1}
	Adding field: `{'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0', 'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1}`

RelativeFieldLocation: 100%|██████████| 1/1 [00:00<00:00, 68.12it/s]
Processes: 100%|██████████| 6/6 [00:08<00:00,  1.39s/it]

In [9]:
missing_keys = dj_table_holder("RoiMask")().list_missing_field()
if len(missing_keys) == 1:
    field_key = missing_keys[0]
elif len(missing_keys) > 1:
    raise ValueError(f"Multiple missing fields found: {missing_keys}")
else:
    print("No missing fields found, using the last field key.")
    all_field_key = dj_table_holder("Field")().proj().fetch(as_dict=True)
    field_key = all_field_key[-1]
    print(f"Field key: {field_key}")

No missing fields found, using the last field key.
Field key: {'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1, 'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0'}

In [10]:
quality_wrapper_filtering_params = {
    "d_qi_min":0.5,
    "qidx_min": 0.5,
    "celltypes": list(range(1,33)),
    "classifier_confidence": 0.25
}
sta_wrapper_filtering_parameters = {
    "rf_qidx_min": 0.5,}

In [16]:
dj_table_holder("RoiMask")()

*experimenter  *date          *exp_num    *raw_id    *field    *region    *cond1    stim_name     cond2       roi_mask
+------------+ +------------+ +---------+ +--------+ +-------+ +--------+ +-------+ +-----------+ +---------+ +--------+
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     gChirp        control     =BLOB=
 (Total: 1)

In [ ]:
#dj_table_holder.clear_tables("rois",field_key=field_key)

[2025-08-21 20:12:37,706][INFO]: Deleting 4 rows from `ageuler_ssuhai_closed_loop`.`roi_mask__roi_mask_presentation`
[2025-08-21 20:12:37,731][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`roi_mask`
[2025-08-21 20:12:39,828][INFO]: Deletes committed.

Removed file: /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/ROIs/M1_LR_GCL0_DN_iter0_ROIs.pkl
Removed file: /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/ROIs/M1_LR_GCL0_Chirp_iter0_ROIs.pkl
Removed file: /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/ROIs/M1_LR_GCL0_MC18_iter0_ROIs.pkl
Removed file: /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/klaudia_data_test/20250717/1/ROIs/M1_LR_GCL0_MB_iter0_ROIs.pkl

In [21]:
# compute 
preprocessor.add_iteration_roi_mask(field_key=field_key)
preprocessor.add_iteration_rois()
preprocessor.add_iteration_traces()

field_key: {'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1, 'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0'}
pres_keys: [{'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1, 'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0', 'stim_name': 'densenoise', 'cond2': 'control'}, {'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1, 'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0', 'stim_name': 'gChirp', 'cond2': 'control'}, {'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1, 'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0', 'stim_name': 'mouse_cam', 'cond2': 'control'}, {'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1, 'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0', 'stim_name': 'movingbar', 'cond2': 'control'}]
No ROI masks found for field: {'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1, 'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0'}
pres_keys: [{'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1, 'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0', 'stim_name': 'densenoise', 'cond2': 'control'}, {'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1, 'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0', 'stim_name': 'gChirp', 'cond2': 'control'}, {'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1, 'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0', 'stim_name': 'mouse_cam', 'cond2': 'control'}, {'experimenter': 'closedlooptest', 'date': datetime.date(2025, 7, 17), 'exp_num': 1, 'raw_id': 1, 'field': 'GCL0', 'region': 'LR', 'cond1': 'iter0', 'stim_name': 'movingbar', 'cond2': 'control'}]
Load model weights for cpu from checkpoint /gpfs01/euler/data/Resources/AutoROIs/models/UNET_v0.1.0/dropout_and_aug_regul.ckpt using config /gpfs01/euler/data/Resources/AutoROIs/models/UNET_v0.1.0/sd_images.yaml

Returned InteractiveRoiCanvas object. To start GUI, call <enter_object_name>.start_gui().

Roi: 100%|██████████| 1/1 [00:00<00:00,  3.95it/s]
Processes: 100%|██████████| 4/4 [00:07<00:00,  1.79s/it]
Processes: 100%|██████████| 428/428 [00:00<00:00, 547.79it/s]

In [ ]:
quality_type_analysis_wrapper.compute_analysis(
    field_key=field_key)

# filter 
passed_roi_ids_chirp_mb = quality_type_analysis_wrapper.get_roi_ids_passing_criterion(field_key=field_key,
    d_qi_min =cfg.quality_filtering["d_qi_min"],
    qidx_min=cfg.quality_filtering["chirp_qi_min"],
    celltypes=cfg.quality_filtering["celltypes"],
    classifier_confidence=quality_wrapper_filtering_params["classifier_confidence"])
if len(passed_roi_ids_chirp_mb) == 0:
    raise ValueError("No ROIs passed the quality criterion for quality and type.")
print(f"ROIs passed quality chirp mb filtering: {passed_roi_ids_chirp_mb}")

ROIs passed quality chirp mb filtering: [12, 15, 18, 27, 30, 36, 42, 45, 63, 66, 69, 78, 81, 90, 93, 102]

In [25]:
sta_wrapper.clear_tables(field_key=field_key)

[2025-09-02 11:00:41,806][INFO]: Deleting 16 rows from `ageuler_ssuhai_closed_loop`.`__s_t_a__data_set`
[2025-09-02 11:00:41,882][INFO]: Deleting 16 rows from `ageuler_ssuhai_closed_loop`.`__fit_gauss2_d_r_f`
[2025-09-02 11:00:41,911][INFO]: Deleting 16 rows from `ageuler_ssuhai_closed_loop`.`__split_r_f`
[2025-09-02 11:00:41,939][INFO]: Deleting 16 rows from `ageuler_ssuhai_closed_loop`.`__s_t_a`
[2025-09-02 11:00:41,968][INFO]: Deleting 16 rows from `ageuler_ssuhai_closed_loop`.`__d_noise_trace`
[2025-09-02 11:00:44,284][INFO]: Deletes committed.
[2025-09-02 11:00:44,316][INFO]: Deleting 0 rows from `ageuler_ssuhai_closed_loop`.`__s_t_a`
[2025-09-02 11:00:44,317][WARNING]: Nothing to delete.
[2025-09-02 11:00:44,348][INFO]: Deleting 0 rows from `ageuler_ssuhai_closed_loop`.`__split_r_f`
[2025-09-02 11:00:44,349][WARNING]: Nothing to delete.
[2025-09-02 11:00:44,379][INFO]: Deleting 0 rows from `ageuler_ssuhai_closed_loop`.`__fit_gauss2_d_r_f`
[2025-09-02 11:00:44,380][WARNING]: Nothing to delete.

In [26]:
# sta 
sta_wrapper.compute_analysis(
    field_key=field_key,
    roi_id_subset=passed_roi_ids_chirp_mb,)

Processes: 100%|██████████| 16/16 [00:05<00:00,  2.78it/s]
Processes: 100%|██████████| 16/16 [00:09<00:00,  1.73it/s]
Processes: 100%|██████████| 16/16 [00:00<00:00, 79.63it/s]
Processes: 100%|██████████| 16/16 [00:00<00:00, 17.71it/s]

In [20]:
assert (dj_table_holder("STA")().fetch("roi_id") == passed_roi_ids_chirp_mb).all(), "STA roi_id does not match passed roi_ids from quality and type filtering."

In [ ]:
# filter
passed_roi_ids_sta = sta_wrapper.get_roi_ids_passing_criterion(field_key=field_key,
                                                               rf_qidx_min=cfg.quality_filtering["rf_qidx_min"])
if len(passed_roi_ids_sta) == 0:
    raise ValueError("No ROIs passed the quality criterion for STA.")
print(f"ROIs passed STA filtering: {passed_roi_ids_sta}")

ROIs passed STA filtering: [15, 27, 30, 36, 42, 45, 63, 66, 69, 78, 81, 90, 93]

In [12]:
dj_table_holder.multiprocessing_threads = 1

In [25]:
random_seed_mei_wrapper.mei_data_container.columns

Index(['readout_idx', 'roi_id', 'mei_id', 'seed', 'mei', 'temporal_kernels',
       'spatial_kernels', 'stability', 'responses_all_readout_idx',
       'mean_responses_all_readout_idx'],
      dtype='object')

In [42]:
random_seed_mei_wrapper.plot1(roi_id = 78)

ROI 78 does not have an MEI. Select among the following:
[15, 27, 30, 42, 45, 63, 66, 69, 81, 90]

In [ ]:
random_seed_mei_wrapper.compute_analysis(field_key=field_key,
                                         roi_id_subset=passed_roi_ids_sta,)

33
Original dataset contains 13 neurons over 1 fields
 ------------------------------------
Dropped 0 fields that did not contain the target cell types (1 remaining)
Overall, dropped 0 neurons of non-target cell types (-0.00%).
 ------------------------------------
Dropped 0 fields with quality indices below threshold (1 remaining)
Overall, dropped 1 neurons over quality checks (-7.69%).
 ------------------------------------
Dropped 0 fields with classifier confidences below 0.25
Overall, dropped 0 neurons with classifier confidences below 0.25 (-0.00%).
 ------------------------------------
 ------------------------------------
Final dataset contains 12 neurons over 1 fields
Total number of cells dropped: 1 (-7.69%)

Upsampling natural spikes traces to get final responses.:   0%|          | 0/1 [00:00<?, ?it/s]

Creating movie dataloaders:   0%|          | 0/1 [00:00<?, ?it/s]

Seed set to 2000
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA A100-PCIE-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
2025-09-02 13:34:42.230660: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/gpfs01/euler/User/ssuhai/.local/lib/python3.12/site-packages/lightning/fabric/loggers/csv_logs.py:268: Experiment logs directory output/csv/ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
/gpfs01/euler/User/ssuhai/.local/lib/python3.12/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /gpfs01/euler/User/ssuhai/output/checkpoints exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name             | Type                        | Params | Mode
-------------------------------------------------------------------------
0 | core             | SimpleCoreWrapper           | 12.4 K | train
1 | readout          | MultiGaussianReadoutWrapper | 64.6 K | train
2 | loss             | PoissonLoss3d               | 0      | train
3 | correlation_loss | CorrelationLoss3d           | 0      | train
-------------------------------------------------------------------------
64.6 K    Trainable params
12.4 K    Non-trainable params
76.9 K    Total params
0.308     Total estimated model params size (MB)
85        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/gpfs01/euler/User/ssuhai/.local/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=63` in the `DataLoader` to improve performance.
/gpfs01/euler/User/ssuhai/.local/lib/python3.12/site-packages/lightning/pytorch/utilities/data.py:123: Your `IterableDataset` has `__len__` defined. In combination with multi-process data loading (when num_workers > 1), `__len__` could be inaccurate if each worker is not configured independently to avoid having duplicate data.
/gpfs01/euler/User/ssuhai/.local/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py:310: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved. New best score: 0.214

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.025 >= min_delta = 0.001. New best score: 0.239

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.004 >= min_delta = 0.001. New best score: 0.243

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.004 >= min_delta = 0.001. New best score: 0.248

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.008 >= min_delta = 0.001. New best score: 0.255

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.010 >= min_delta = 0.001. New best score: 0.265

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.009 >= min_delta = 0.001. New best score: 0.274

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.008 >= min_delta = 0.001. New best score: 0.282

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.006 >= min_delta = 0.001. New best score: 0.288

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.003 >= min_delta = 0.001. New best score: 0.291

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.003 >= min_delta = 0.001. New best score: 0.294

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.001 >= min_delta = 0.001. New best score: 0.295

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.001 >= min_delta = 0.001. New best score: 0.296

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.002 >= min_delta = 0.001. New best score: 0.298

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Monitored metric val_correlation did not improve in the last 10 records. Best score: 0.298. Signaling Trainer to stop.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃       DataLoader 1        ┃       DataLoader 2        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│     test_correlation      │    0.2206917405128479     │    0.2989720106124878     │    0.43967872858047485    │
│         test_loss         │      159.53759765625      │    123.60511779785156     │    10.533097267150879     │
└───────────────────────────┴───────────────────────────┴───────────────────────────┴───────────────────────────┘

Seed set to 4000
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name             | Type                        | Params | Mode
-------------------------------------------------------------------------
0 | core             | SimpleCoreWrapper           | 12.4 K | train
1 | readout          | MultiGaussianReadoutWrapper | 64.6 K | train
2 | loss             | PoissonLoss3d               | 0      | train
3 | correlation_loss | CorrelationLoss3d           | 0      | train
-------------------------------------------------------------------------
64.6 K    Trainable params
12.4 K    Non-trainable params
76.9 K    Total params
0.308     Total estimated model params size (MB)
85        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved. New best score: 0.207

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.029 >= min_delta = 0.001. New best score: 0.237

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.010 >= min_delta = 0.001. New best score: 0.247

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.007 >= min_delta = 0.001. New best score: 0.254

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.007 >= min_delta = 0.001. New best score: 0.261

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.007 >= min_delta = 0.001. New best score: 0.268

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.006 >= min_delta = 0.001. New best score: 0.274

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.005 >= min_delta = 0.001. New best score: 0.279

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.005 >= min_delta = 0.001. New best score: 0.284

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.005 >= min_delta = 0.001. New best score: 0.289

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.002 >= min_delta = 0.001. New best score: 0.291

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Monitored metric val_correlation did not improve in the last 10 records. Best score: 0.291. Signaling Trainer to stop.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃       DataLoader 1        ┃       DataLoader 2        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│     test_correlation      │    0.2436603605747223     │    0.29066765308380127    │    0.43198880553245544    │
│         test_loss         │    161.18890380859375     │    124.58027648925781     │    10.625062942504883     │
└───────────────────────────┴───────────────────────────┴───────────────────────────┴───────────────────────────┘

Seed set to 3000
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name             | Type                        | Params | Mode
-------------------------------------------------------------------------
0 | core             | SimpleCoreWrapper           | 12.4 K | train
1 | readout          | MultiGaussianReadoutWrapper | 64.6 K | train
2 | loss             | PoissonLoss3d               | 0      | train
3 | correlation_loss | CorrelationLoss3d           | 0      | train
-------------------------------------------------------------------------
64.6 K    Trainable params
12.4 K    Non-trainable params
76.9 K    Total params
0.308     Total estimated model params size (MB)
85        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved. New best score: 0.211

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.020 >= min_delta = 0.001. New best score: 0.231

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.009 >= min_delta = 0.001. New best score: 0.240

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.009 >= min_delta = 0.001. New best score: 0.250

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.010 >= min_delta = 0.001. New best score: 0.259

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.010 >= min_delta = 0.001. New best score: 0.269

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.011 >= min_delta = 0.001. New best score: 0.280

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.008 >= min_delta = 0.001. New best score: 0.289

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.009 >= min_delta = 0.001. New best score: 0.298

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.008 >= min_delta = 0.001. New best score: 0.306

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.007 >= min_delta = 0.001. New best score: 0.313

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.005 >= min_delta = 0.001. New best score: 0.318

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.003 >= min_delta = 0.001. New best score: 0.321

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Monitored metric val_correlation did not improve in the last 10 records. Best score: 0.321. Signaling Trainer to stop.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃       DataLoader 1        ┃       DataLoader 2        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│     test_correlation      │    0.2629484534263611     │    0.32213184237480164    │      0.4521504342556      │
│         test_loss         │     159.8658447265625     │    123.08631896972656     │    10.557760238647461     │
└───────────────────────────┴───────────────────────────┴───────────────────────────┴───────────────────────────┘

Seed set to 0
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name             | Type                        | Params | Mode
-------------------------------------------------------------------------
0 | core             | SimpleCoreWrapper           | 12.4 K | train
1 | readout          | MultiGaussianReadoutWrapper | 64.6 K | train
2 | loss             | PoissonLoss3d               | 0      | train
3 | correlation_loss | CorrelationLoss3d           | 0      | train
-------------------------------------------------------------------------
64.6 K    Trainable params
12.4 K    Non-trainable params
76.9 K    Total params
0.308     Total estimated model params size (MB)
85        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved. New best score: 0.178

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.033 >= min_delta = 0.001. New best score: 0.211

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.017 >= min_delta = 0.001. New best score: 0.228

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.015 >= min_delta = 0.001. New best score: 0.243

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.012 >= min_delta = 0.001. New best score: 0.255

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.011 >= min_delta = 0.001. New best score: 0.266

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.011 >= min_delta = 0.001. New best score: 0.277

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.010 >= min_delta = 0.001. New best score: 0.287

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.007 >= min_delta = 0.001. New best score: 0.294

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.006 >= min_delta = 0.001. New best score: 0.300

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.004 >= min_delta = 0.001. New best score: 0.305

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.003 >= min_delta = 0.001. New best score: 0.307

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.002 >= min_delta = 0.001. New best score: 0.309

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.001 >= min_delta = 0.001. New best score: 0.310

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.002 >= min_delta = 0.001. New best score: 0.312

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Monitored metric val_correlation did not improve in the last 10 records. Best score: 0.312. Signaling Trainer to stop.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃       DataLoader 1        ┃       DataLoader 2        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│     test_correlation      │    0.2343219667673111     │    0.3119274973869324     │    0.4457942843437195     │
│         test_loss         │         159.8125          │    124.11891174316406     │    10.515005111694336     │
└───────────────────────────┴───────────────────────────┴───────────────────────────┴───────────────────────────┘

Seed set to 1000
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name             | Type                        | Params | Mode
-------------------------------------------------------------------------
0 | core             | SimpleCoreWrapper           | 12.4 K | train
1 | readout          | MultiGaussianReadoutWrapper | 64.6 K | train
2 | loss             | PoissonLoss3d               | 0      | train
3 | correlation_loss | CorrelationLoss3d           | 0      | train
-------------------------------------------------------------------------
64.6 K    Trainable params
12.4 K    Non-trainable params
76.9 K    Total params
0.308     Total estimated model params size (MB)
85        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved. New best score: 0.245

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.023 >= min_delta = 0.001. New best score: 0.268

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.005 >= min_delta = 0.001. New best score: 0.272

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.008 >= min_delta = 0.001. New best score: 0.280

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.008 >= min_delta = 0.001. New best score: 0.288

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.009 >= min_delta = 0.001. New best score: 0.296

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.006 >= min_delta = 0.001. New best score: 0.303

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.005 >= min_delta = 0.001. New best score: 0.308

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.004 >= min_delta = 0.001. New best score: 0.311

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.004 >= min_delta = 0.001. New best score: 0.316

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_correlation improved by 0.001 >= min_delta = 0.001. New best score: 0.317

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Monitored metric val_correlation did not improve in the last 10 records. Best score: 0.317. Signaling Trainer to stop.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃       DataLoader 1        ┃       DataLoader 2        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│     test_correlation      │    0.2336820662021637     │    0.31713590025901794    │    0.4623575210571289     │
│         test_loss         │    159.20602416992188     │    123.52301788330078     │    10.526517868041992     │
└───────────────────────────┴───────────────────────────┴───────────────────────────┴───────────────────────────┘

Filtered neurons based on testset correlation: 12 -> 10

Seed set to 111

Generating unstable MEIs for neurons (readout idx): [2, 6].

Seed set to 222

Done with meis in phase unstable.
Start decomposing ...
Decomposing MEIs for neuron (readout idx) 2 ...
Decomposing MEIs for neuron (readout idx) 6 ...
Generating stable MEIs for neurons (readout idx): [0, 1, 4, 5, 7, 8, 9, 10].

Seed set to 111

Done with meis in phase stable.
Start decomposing ...
Decomposing MEIs for neuron (readout idx) 0 ...
Decomposing MEIs for neuron (readout idx) 1 ...
Decomposing MEIs for neuron (readout idx) 4 ...
Decomposing MEIs for neuron (readout idx) 5 ...
Decomposing MEIs for neuron (readout idx) 7 ...
Decomposing MEIs for neuron (readout idx) 8 ...
Decomposing MEIs for neuron (readout idx) 9 ...
Decomposing MEIs for neuron (readout idx) 10 ...
Generating responses for neurons in readout 10 to all meis 12 ...

In [38]:
print(2)
random_seed_mei_wrapper.mei_subanalysis()

[2025-09-02 12:59:08,733][WARNING]: MySQL server has gone away. Reconnecting to the server.
--- Logging error ---
Traceback (most recent call last):
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/connection.py", line 343, in query
    self._execute_query(cursor, query, args, suppress_warnings)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/connection.py", line 299, in _execute_query
    raise translate_query_error(err, query)
datajoint.errors.LostConnectionError: ('Server connection lost', 'Lost connection to MySQL server during query')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/logging/__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/asyncio/base_events.py", line 640, in run_forever
    self._run_once()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/asyncio/base_events.py", line 1992, in _run_once
    handle._run()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_3109086/524131253.py", line 1, in <module>
    print(2)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2185, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, trace_suspend_type, from_this_thread, frames_tracker)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2245, in _do_wait_suspend
    internal_cmd.do_it(self)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 565, in do_it
    self.method(dbg, *self.args, **self.kwargs)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py", line 531, in new_func
    return func(*args, **kwargs)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 800, in internal_get_variable_json
    variables.append(child_var.get_var_data(fmt=fmt))
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_suspended_frames.py", line 57, in get_var_data
    type_name, _type_qualifier, _is_exception_on_eval, resolver, value = get_variable_details(
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_xml.py", line 351, in get_variable_details
    value = to_string(v)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_safe_repr.py", line 78, in __call__
    return "".join(self._repr(obj, 0))
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_safe_repr.py", line 258, in _repr_dict
    for p in self._repr(item, 100 if item is obj else level + 1):
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_safe_repr.py", line 343, in _repr_obj
    obj_repr = repr(obj)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/expression.py", line 671, in __repr__
    else self.preview()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/expression.py", line 676, in preview
    return preview(self, limit, width)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/preview.py", line 13, in preview
    tuples = rel.fetch(limit=limit + 1, format="array")
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/fetch.py", line 236, in __call__
    cur = self._expression.cursor(as_dict=as_dict)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/expression.py", line 658, in cursor
    return self.connection.query(sql, as_dict=as_dict)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/connection.py", line 347, in query
    logger.warning("MySQL server has gone away. Reconnecting to the server.")
Message: 'MySQL server has gone away. Reconnecting to the server.'
Arguments: ()

2

Seed set to 111

Generating unstable MEIs for neurons (readout idx): [0, 4].

Seed set to 222

Start decomposing ...
Generating stable MEIs for neurons (readout idx): [1, 2, 5, 6, 7, 8].

Seed set to 111

Start decomposing ...

KeyboardInterrupt:

In [ ]:
random_seed_mei_wrapper.get_responses_and_add_to_container()

In [56]:
random_seed_mei_wrapper.mei_data_container[["readout_idx","stability","mean_responses_all_readout_idx"]]

   readout_idx stability                     mean_responses_all_readout_idx
0            0  unstable  [3.0669007, 1.0788754, 1.297539, 1.2112863, 2....
1            0  unstable  [2.6983378, 0.85414314, 1.2265472, 1.2419125, ...
2            4  unstable  [2.7701602, 0.8902386, 1.1621171, 1.1370437, 2...
3            4  unstable  [2.5725436, 0.77136815, 1.0902089, 1.0614189, ...
4            1    stable  [2.805798, 5.4680963, 4.30828, 2.7747808, 2.34...
5            2    stable  [1.7774045, 5.565527, 5.451215, 2.815146, 1.49...
6            5    stable  [2.4266973, 5.3656087, 4.629107, 2.9815748, 1....
7            6    stable  [2.2289875, 6.3084893, 6.1097903, 2.7270772, 2...
8            7    stable  [1.8777401, 5.3634477, 4.9427295, 2.8802845, 1...
9            8    stable  [2.7347972, 5.199195, 4.1092043, 2.9845207, 2....

In [1]:
print("eef")

eef

In [ ]:
#random_seed_mei_wrapper.upload_to_db()

In [49]:
dj_table_holder("OnlineMEIs")()

[2025-08-24 17:06:11,581][WARNING]: MySQL server has gone away. Reconnecting to the server.
--- Logging error ---
Traceback (most recent call last):
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/connection.py", line 343, in query
    self._execute_query(cursor, query, args, suppress_warnings)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/connection.py", line 299, in _execute_query
    raise translate_query_error(err, query)
datajoint.errors.LostConnectionError: ('Connection timed out', "MySQL server has gone away (SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2417)'))")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/logging/__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/asyncio/base_events.py", line 640, in run_forever
    self._run_once()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/asyncio/base_events.py", line 1992, in _run_once
    handle._run()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1368882/4144297477.py", line 1, in <module>
    dj_table_holder("OnlineMEIs")()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/displayhook.py", line 268, in __call__
    format_dict, md_dict = self.compute_format_data(result)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/displayhook.py", line 157, in compute_format_data
    return self.shell.display_formatter.format(result)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/formatters.py", line 238, in format
    data = formatter(obj)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/formatters.py", line 282, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/core/formatters.py", line 770, in __call__
    printer.pretty(obj)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/lib/pretty.py", line 419, in pretty
    return _repr_pprint(obj, self, cycle)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/IPython/lib/pretty.py", line 794, in _repr_pprint
    output = repr(obj)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/expression.py", line 671, in __repr__
    else self.preview()
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/expression.py", line 676, in preview
    return preview(self, limit, width)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/preview.py", line 13, in preview
    tuples = rel.fetch(limit=limit + 1, format="array")
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/fetch.py", line 236, in __call__
    cur = self._expression.cursor(as_dict=as_dict)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/expression.py", line 658, in cursor
    return self.connection.query(sql, as_dict=as_dict)
  File "/.pyenv/versions/miniconda3-latest/lib/python3.12/site-packages/datajoint/connection.py", line 347, in query
    logger.warning("MySQL server has gone away. Reconnecting to the server.")
Message: 'MySQL server has gone away. Reconnecting to the server.'
Arguments: ()

*experimenter  *date          *exp_num    *raw_id    *field    *region    *cond1    *session_name  *roi_id    *readout_idx   *seed    mei
+------------+ +------------+ +---------+ +--------+ +-------+ +--------+ +-------+ +------------+ +--------+ +------------+ +------+ +--------+
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 21         1              111      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 21         1              222      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 24         2              111      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 24         2              222      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 27         3              111      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 27         3              222      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 36         4              111      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 36         4              222      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 39         5              111      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 39         5              222      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 42         6              111      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 42         6              222      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 45         7              111      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 45         7              222      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 48         8              111      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 48         8              222      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 51         9              111      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 51         9              222      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 60         10             111      =BLOB=
closedlooptest 2025-07-17     1           1          GCL0      LR         iter0     online_session 60         10             222      =BLOB=
   ...
 (Total: 32)

In [9]:
# somehow I get a circular import error if I import this at the top
from simulations.gui.integrated_autorois import InteractiveRoiCanvas

In [10]:
online_analysis_gui = InteractiveRoiCanvas(
    dj_table_holder=dj_table_holder,
    dj_preprocessor=preprocessor,
    all_dj_wrappers=[quality_type_analysis_wrapper,sta_wrapper,random_seed_mei_wrapper],
    field_key=field_key,
    take_roi_rgba_from_this_analysis=random_seed_mei_wrapper.name,  # specify which analysis to take the roi color and alpha from
    canvas_width=30,
    )

NameError: name 'field_key' is not defined

In [79]:
display(online_analysis_gui.start_gui())

HBox(children=(VBox(children=(Dropdown(description='Change Mode:', layout=Layout(width='200px'), options=('ROI…

In [36]:
display(online_analysis_gui.start_gui())

HBox(children=(VBox(children=(Dropdown(description='Change Mode:', layout=Layout(width='200px'), options=('ROI…

# The stimulus

In [37]:
roi_ids,seeds =dj_table_holder("OnlineMEIs")().fetch("roi_id","seed")

In [52]:
roi_seed = list(zip(roi_ids[:7],seeds[:7]))
print(f"roi_seed: {roi_seed}")

roi_seed: [(21, 111), (21, 222), (24, 111), (24, 222), (27, 111), (27, 222), (36, 111)]

In [ ]:
roi_id2mei_id,roi_id2mei_info = random_seed_mei_wrapper.select_subset_of_meis_for_each_roi()

2

In [18]:
random_seed_mei_wrapper.mei_data_container[["readout_idx","stability","roi_id","seed","mei_id"]]

    readout_idx stability  roi_id  seed           mei_id
0             2  unstable      30   111  roi_30_seed_111
1             2  unstable      30   222  roi_30_seed_222
2             6  unstable      63   111  roi_63_seed_111
3             6  unstable      63   222  roi_63_seed_222
4             0    stable      15   111  roi_15_seed_111
5             1    stable      27   111  roi_27_seed_111
6             4    stable      42   111  roi_42_seed_111
7             5    stable      45   111  roi_45_seed_111
8             7    stable      66   111  roi_66_seed_111
9             8    stable      69   111  roi_69_seed_111
10            9    stable      81   111  roi_81_seed_111
11           10    stable      90   111  roi_90_seed_111

In [19]:
roi_seed = [(30,111),
            (30,222),
            (63,111),
            (63,222),
            (15,111),
            (27,111),
            (42,111),
            (45,111)]

In [22]:
print(2)
create_single_mei_avis_and_metadata(
    rois_seed=roi_seed,
    roi_id2mei_ids = roi_id2mei_id,    
    mei_data_container=random_seed_mei_wrapper.mei_data_container,
    stimulus_table=dj_table_holder("Stimulus")(),
    fit_gauss_2d_rf_table= dj_table_holder("FitGauss2DRF")(),
    abs_save_dir=cfg.paths.stimulus_output_dir,
)

2
Found 6 rois in the FitGauss2D table.
Initial roi_id order: [15, 27, 30, 42, 45, 63].
Reordered roi_id order: [42, 27, 63, 30, 45, 15].
Generated MEI presentation ordering: [['roi_42_seed_111', 'roi_81_seed_111', 'roi_69_seed_111', 'roi_27_seed_111', 'roi_66_seed_111', 'roi_30_seed_111'], ['roi_45_seed_111', 'roi_66_seed_111', 'roi_81_seed_111', 'roi_27_seed_111', 'roi_63_seed_222', 'roi_30_seed_111'], ['roi_27_seed_111', 'roi_63_seed_222', 'roi_42_seed_111', 'roi_69_seed_111', 'roi_63_seed_111', 'roi_90_seed_111'], ['roi_30_seed_111', 'roi_66_seed_111', 'roi_42_seed_111', 'roi_90_seed_111', 'roi_69_seed_111', 'roi_30_seed_222'], ['roi_90_seed_111', 'roi_63_seed_222', 'roi_45_seed_111', 'roi_30_seed_111', 'roi_27_seed_111', 'roi_69_seed_111'], ['roi_42_seed_111', 'roi_30_seed_111', 'roi_81_seed_111', 'roi_69_seed_111', 'roi_66_seed_111', 'roi_15_seed_111']].
Creating MEI avi file for roi_30_seed_111 at /gpfs01/euler/data/Data/Suhai/stimuli_closed_loop/iter9/mei_roi_30_seed_111.avi.
Creating MEI avi file for roi_30_seed_222 at /gpfs01/euler/data/Data/Suhai/stimuli_closed_loop/iter9/mei_roi_30_seed_222.avi.
Creating MEI avi file for roi_63_seed_111 at /gpfs01/euler/data/Data/Suhai/stimuli_closed_loop/iter9/mei_roi_63_seed_111.avi.
Creating MEI avi file for roi_63_seed_222 at /gpfs01/euler/data/Data/Suhai/stimuli_closed_loop/iter9/mei_roi_63_seed_222.avi.
Creating MEI avi file for roi_15_seed_111 at /gpfs01/euler/data/Data/Suhai/stimuli_closed_loop/iter9/mei_roi_15_seed_111.avi.
Creating MEI avi file for roi_27_seed_111 at /gpfs01/euler/data/Data/Suhai/stimuli_closed_loop/iter9/mei_roi_27_seed_111.avi.
Creating MEI avi file for roi_42_seed_111 at /gpfs01/euler/data/Data/Suhai/stimuli_closed_loop/iter9/mei_roi_42_seed_111.avi.
Creating MEI avi file for roi_45_seed_111 at /gpfs01/euler/data/Data/Suhai/stimuli_closed_loop/iter9/mei_roi_45_seed_111.avi.
Retrieved and saved MEIs with the following unique ids: ['roi_30_seed_111', 'roi_30_seed_222', 'roi_63_seed_111', 'roi_63_seed_222', 'roi_15_seed_111', 'roi_27_seed_111', 'roi_42_seed_111', 'roi_45_seed_111'].
Saved metadata file at /gpfs01/euler/data/Data/Suhai/stimuli_closed_loop/iter9/mei_metadata.yaml.
DONE!

# Clean up

In [32]:
userinput = input("Cleanup? (y/n): ")
if userinput.lower() == 'y':
    dj_table_holder.clear_tables("all")

[2025-08-12 18:21:27,897][INFO]: Deleting 3 rows from `ageuler_ssuhai_closed_loop`.`__field__stack_averages`
[2025-08-12 18:21:27,964][INFO]: Deleting 3 rows from `ageuler_ssuhai_closed_loop`.`__presentation__scan_info`
[2025-08-12 18:21:28,010][INFO]: Deleting 9 rows from `ageuler_ssuhai_closed_loop`.`__presentation__stack_averages`
[2025-08-12 18:21:28,150][INFO]: Deleting 97 rows from `ageuler_ssuhai_closed_loop`.`__peak_s_t_a_position`
[2025-08-12 18:21:28,200][INFO]: Deleting 97 rows from `ageuler_ssuhai_closed_loop`.`__s_t_a__data_set`
[2025-08-12 18:21:28,253][INFO]: Deleting 97 rows from `ageuler_ssuhai_closed_loop`.`__split_r_f`
[2025-08-12 18:21:28,290][INFO]: Deleting 97 rows from `ageuler_ssuhai_closed_loop`.`__s_t_a`
[2025-08-12 18:21:28,323][INFO]: Deleting 97 rows from `ageuler_ssuhai_closed_loop`.`__d_noise_trace`
[2025-08-12 18:21:28,465][INFO]: Deleting 95 rows from `ageuler_ssuhai_closed_loop`.`__celltype_assignment`
[2025-08-12 18:21:28,496][INFO]: Deleting 95 rows from `ageuler_ssuhai_closed_loop`.`__baden16_traces`
[2025-08-12 18:21:28,552][INFO]: Deleting 192 rows from `ageuler_ssuhai_closed_loop`.`__averages`
[2025-08-12 18:21:28,592][INFO]: Deleting 97 rows from `ageuler_ssuhai_closed_loop`.`__chirp_q_i`
[2025-08-12 18:21:28,657][INFO]: Deleting 95 rows from `ageuler_ssuhai_closed_loop`.`__os_ds_indexes`
[2025-08-12 18:21:28,698][INFO]: Deleting 192 rows from `ageuler_ssuhai_closed_loop`.`__snippets`
[2025-08-12 18:21:28,751][INFO]: Deleting 289 rows from `ageuler_ssuhai_closed_loop`.`__preprocess_traces`
[2025-08-12 18:21:28,784][INFO]: Deleting 289 rows from `ageuler_ssuhai_closed_loop`.`__traces`
[2025-08-12 18:21:28,824][INFO]: Deleting 3 rows from `ageuler_ssuhai_closed_loop`.`roi_mask__roi_mask_presentation`
[2025-08-12 18:21:28,899][INFO]: Deleting 101 rows from `ageuler_ssuhai_closed_loop`.`__roi`
[2025-08-12 18:21:28,923][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`roi_mask`
[2025-08-12 18:21:28,948][INFO]: Deleting 3 rows from `ageuler_ssuhai_closed_loop`.`__presentation`
[2025-08-12 18:21:28,992][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`__relative_field_location`
[2025-08-12 18:21:29,015][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`__field`
[2025-08-12 18:21:29,054][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`__optic_disk`
[2025-08-12 18:21:29,084][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`#raw_data_params`
[2025-08-12 18:21:29,141][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`__experiment__animal`
[2025-08-12 18:21:29,184][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`__experiment__exp_info`
[2025-08-12 18:21:29,227][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`__experiment__indicator`
[2025-08-12 18:21:29,270][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`__experiment__pharm_info`
[2025-08-12 18:21:29,293][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`__experiment`
[2025-08-12 18:21:29,317][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`user_info`
[2025-08-12 18:21:31,871][INFO]: Deletes committed.
[2025-08-12 18:21:31,917][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`#d_noise_trace_params`
[2025-08-12 18:21:31,960][INFO]: Deleting 6 rows from `ageuler_ssuhai_closed_loop`.`#preprocess_params`
[2025-08-12 18:21:32,001][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`#cascade_trace_params`
[2025-08-12 18:21:32,025][INFO]: Deleting 6 rows from `ageuler_ssuhai_closed_loop`.`stimulus`
[2025-08-12 18:21:33,547][INFO]: Deletes committed.
[2025-08-12 18:21:33,573][INFO]: Deleting 0 rows from `ageuler_ssuhai_closed_loop`.`#raw_data_params`
[2025-08-12 18:21:33,575][WARNING]: Nothing to delete.
[2025-08-12 18:21:33,603][INFO]: Deleting 0 rows from `ageuler_ssuhai_closed_loop`.`#preprocess_params`
[2025-08-12 18:21:33,604][WARNING]: Nothing to delete.
[2025-08-12 18:21:33,648][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`__classifier`
[2025-08-12 18:21:33,672][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`#classifier_method`
[2025-08-12 18:21:35,102][INFO]: Deletes committed.
[2025-08-12 18:21:35,128][INFO]: Deleting 0 rows from `ageuler_ssuhai_closed_loop`.`__classifier`
[2025-08-12 18:21:35,129][WARNING]: Nothing to delete.
[2025-08-12 18:21:35,158][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`classifier_training_data`
[2025-08-12 18:21:36,724][INFO]: Deletes committed.
[2025-08-12 18:21:36,751][INFO]: Deleting 0 rows from `ageuler_ssuhai_closed_loop`.`#cascade_trace_params`
[2025-08-12 18:21:36,752][WARNING]: Nothing to delete.
[2025-08-12 18:21:36,780][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`#cascade_params`
[2025-08-12 18:21:38,081][INFO]: Deletes committed.
[2025-08-12 18:21:38,108][INFO]: Deleting 0 rows from `ageuler_ssuhai_closed_loop`.`#d_noise_trace_params`
[2025-08-12 18:21:38,109][WARNING]: Nothing to delete.
[2025-08-12 18:21:38,137][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`#s_t_a_params`
[2025-08-12 18:21:39,500][INFO]: Deletes committed.
[2025-08-12 18:21:39,527][INFO]: Deleting 1 rows from `ageuler_ssuhai_closed_loop`.`#split_r_f_params`
[2025-08-12 18:21:41,045][INFO]: Deletes committed.